services:
  observability.mongo:
    restart: always
    image: mongo
    container_name: observability.mongo.db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27030:27017"
    volumes:
      - mongo.db.observability.volume:/data/db
  observability.mongo.ui:
    restart: always
    image: mongo-express
    container_name: observability.mongo.db.ui
    ports:
      - "27032:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo.db.observability:27017/
      ME_CONFIG_BASICAUTH: false

  seq:
    image: datalust/seq:latest
    container_name: observability.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

volumes:
  mongo.db.observability.volume: